package com.example.lizhengjun.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.day09lianxicejiu.api.SjBean;

import com.example.lizhengjun.dao.SjBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sjBeanDaoConfig;

    private final SjBeanDao sjBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sjBeanDaoConfig = daoConfigMap.get(SjBeanDao.class).clone();
        sjBeanDaoConfig.initIdentityScope(type);

        sjBeanDao = new SjBeanDao(sjBeanDaoConfig, this);

        registerDao(SjBean.class, sjBeanDao);
    }
    
    public void clear() {
        sjBeanDaoConfig.clearIdentityScope();
    }

    public SjBeanDao getSjBeanDao() {
        return sjBeanDao;
    }

}
